# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
from dataclasses import dataclass
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import platform


# Used for default argument values
_DEFAULT = object() # type: typing.Any

import ctypes
import struct

class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_kon_parser_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_kon_parser_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_kon_parser_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError(f"junk data left in buffer at end of consume_with_stream {s.remaining()}")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError(f"junk data left in buffer at end of read_with_stream {s.remaining()}")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiFfiConverterByRefBytes:
    """Zero-copy converter for `&[u8]` / `[ByRef] bytes` arguments.

    Only `lower` and `check_lower` are valid — zero-copy byte buffers only
    flow foreign -> Rust, and only in argument position. `lift`, `read`, and
    `write` have no sound implementation here.

    CPython `bytes` objects are immutable and their internal buffer doesn't
    move for the lifetime of the object; the caller must keep the source
    `bytes` alive for the duration of the FFI call.
    """

    @staticmethod
    def check_lower(value):
        # Tighter than `bytes-like`: `lower` uses `ctypes.c_char_p` which only
        # accepts `bytes`/`None`, so fail fast with a matching check.
        if not isinstance(value, bytes):
            raise TypeError("a bytes object is required, not {!r}".format(type(value).__name__))

    @staticmethod
    def lower(value):
        fb = _UniffiForeignBytes()
        if len(value) == 0:
            fb.len = 0
            fb.data = None
        else:
            fb.len = len(value)
            fb.data = ctypes.cast(ctypes.c_char_p(value), ctypes.POINTER(ctypes.c_char))
        return fb

    @staticmethod
    def lift(value):
        raise NotImplementedError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")

    @staticmethod
    def read(buf):
        raise NotImplementedError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    @staticmethod
    def write(value, buf):
        raise NotImplementedError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            packed = struct.pack(format, value)
            if size > 0:
                ctypes.memmove(ctypes.addressof(self.rbuf.data.contents) + self.rbuf.len, packed, size)
    
    def write(self, value):
        length = len(value)
        with self._reserve(length):
            if length > 0:
                ctypes.memmove(ctypes.addressof(self.rbuf.data.contents) + self.rbuf.len, value, length)

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiFfiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))
# Initial value and increment amount for handles. 
# These ensure that Python-generated handles always have the lowest bit set
_UNIFFI_HANDLEMAP_INITIAL = 1
_UNIFFI_HANDLEMAP_DELTA = 2

class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = _UNIFFI_HANDLEMAP_INITIAL

    def insert(self, obj):
        with self._lock:
            return self._insert(obj)

    """Low-level insert, this assumes `self._lock` is held."""
    def _insert(self, obj):
        handle = self._counter
        self._counter += _UNIFFI_HANDLEMAP_DELTA
        self._map[handle] = obj
        return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.get: Invalid handle {handle}")

    def clone(self, handle):
        try:
            with self._lock:
                obj = self._map[handle]
                return self._insert(obj)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.clone: Invalid handle {handle}")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.remove: Invalid handle: {handle}")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("kon_parser")
    path = os.path.join(os.path.dirname(__file__), libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 30
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_kon_parser_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    if lib.uniffi_kon_parser_checksum_func_parse() != 39827:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UniffiLib.ffi_kon_parser_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_kon_parser_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_kon_parser_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_kon_parser_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_kon_parser_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_kon_parser_rustbuffer_free.restype = None
_UniffiLib.ffi_kon_parser_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_kon_parser_rustbuffer_reserve.restype = _UniffiRustBuffer
_UniffiLib.ffi_kon_parser_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_kon_parser_uniffi_contract_version.restype = ctypes.c_uint32
_UniffiLib.uniffi_kon_parser_checksum_func_parse.argtypes = (
)
_UniffiLib.uniffi_kon_parser_checksum_func_parse.restype = ctypes.c_uint16
_UniffiLib.uniffi_kon_parser_fn_func_parse.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_kon_parser_fn_func_parse.restype = _UniffiRustBuffer

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)



# Public interface members begin here.


class _UniffiFfiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()

@dataclass
class Param:
    def __init__(self, *, name:str, ty:str):
        self.name = name
        self.ty = ty
        
        

    
    def __str__(self):
        return "Param(name={}, ty={})".format(self.name, self.ty)
    def __eq__(self, other):
        if self.name != other.name:
            return False
        if self.ty != other.ty:
            return False
        return True

class _UniffiFfiConverterTypeParam(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return Param(
            name=_UniffiFfiConverterString.read(buf),
            ty=_UniffiFfiConverterString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.name)
        _UniffiFfiConverterString.check_lower(value.ty)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.name, buf)
        _UniffiFfiConverterString.write(value.ty, buf)

class _UniffiFfiConverterSequenceTypeParam(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterTypeParam.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterTypeParam.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterTypeParam.read(buf) for i in range(count)
        ]

@dataclass
class InterfaceMethod:
    def __init__(self, *, name:str, params:typing.List[Param]):
        self.name = name
        self.params = params
        
        

    
    def __str__(self):
        return "InterfaceMethod(name={}, params={})".format(self.name, self.params)
    def __eq__(self, other):
        if self.name != other.name:
            return False
        if self.params != other.params:
            return False
        return True

class _UniffiFfiConverterTypeInterfaceMethod(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return InterfaceMethod(
            name=_UniffiFfiConverterString.read(buf),
            params=_UniffiFfiConverterSequenceTypeParam.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.name)
        _UniffiFfiConverterSequenceTypeParam.check_lower(value.params)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.name, buf)
        _UniffiFfiConverterSequenceTypeParam.write(value.params, buf)

class _UniffiFfiConverterFloat64(_UniffiConverterPrimitiveFloat):
    @staticmethod
    def read(buf):
        return buf.read_double()

    @staticmethod
    def write(value, buf):
        buf.write_double(value)

class _UniffiFfiConverterBoxTypeExpr(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        _UniffiFfiConverterTypeExpr.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        _UniffiFfiConverterTypeExpr.write(value, buf)

    @classmethod
    def read(cls, buf):
        return _UniffiFfiConverterTypeExpr.read(buf)

class _UniffiFfiConverterOptionalString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterString.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterString.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterString.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")






class StringPart:
    def __init__(self):
        raise RuntimeError("StringPart cannot be instantiated directly")

    # Each enum variant is a nested class of the enum itself.
    @dataclass
    class LITERAL:
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"StringPart.LITERAL{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, StringPart):
                return NotImplemented
            if not other.is_LITERAL():
                return False
            return self._values == other._values

    @dataclass
    class INTERP:
        
        def __init__(self, expr:Expr, format:typing.Optional[str]):
            self.expr = expr
            
            
            self.format = format
            
            
            pass

    
            
            
    
        def __str__(self):
            return "StringPart.INTERP(expr={}, format={})".format(self.expr, self.format)
        def __eq__(self, other):
            if not isinstance(other, StringPart):
                return NotImplemented
            if not other.is_INTERP():
                return False
            if self.expr != other.expr:
                return False
            if self.format != other.format:
                return False
            return True

    

    # For each variant, we have `is_NAME` and `is_name` methods for easily checking
    # whether an instance is that variant.
    def is_LITERAL(self) -> bool:
        return isinstance(self, StringPart.LITERAL)
    def is_literal(self) -> bool:
        return isinstance(self, StringPart.LITERAL)
    def is_INTERP(self) -> bool:
        return isinstance(self, StringPart.INTERP)
    def is_interp(self) -> bool:
        return isinstance(self, StringPart.INTERP)
    

# Now, a little trick - we make each nested variant class be a subclass of the main
# enum class, so that method calls and instance checks etc will work intuitively.
# We might be able to do this a little more neatly with a metaclass, but this'll do.
StringPart.LITERAL = type("StringPart.LITERAL", (StringPart.LITERAL, StringPart,), {})  # type: ignore
StringPart.INTERP = type("StringPart.INTERP", (StringPart.INTERP, StringPart,), {})  # type: ignore




class _UniffiFfiConverterTypeStringPart(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return StringPart.LITERAL(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 2:
            return StringPart.INTERP(
                _UniffiFfiConverterBoxTypeExpr.read(buf),
                _UniffiFfiConverterOptionalString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value.is_LITERAL():
            _UniffiFfiConverterString.check_lower(value._values[0])
            return
        if value.is_INTERP():
            _UniffiFfiConverterBoxTypeExpr.check_lower(value.expr)
            _UniffiFfiConverterOptionalString.check_lower(value.format)
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value.is_LITERAL():
            buf.write_i32(1)
            _UniffiFfiConverterString.write(value._values[0], buf)
        if value.is_INTERP():
            buf.write_i32(2)
            _UniffiFfiConverterBoxTypeExpr.write(value.expr, buf)
            _UniffiFfiConverterOptionalString.write(value.format, buf)



class _UniffiFfiConverterSequenceTypeStringPart(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterTypeStringPart.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterTypeStringPart.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterTypeStringPart.read(buf) for i in range(count)
        ]






class BinOp(enum.Enum):
    
    ADD = 0
    
    SUB = 1
    
    MUL = 2
    
    DIV = 3
    


class _UniffiFfiConverterTypeBinOp(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return BinOp.ADD
        if variant == 2:
            return BinOp.SUB
        if variant == 3:
            return BinOp.MUL
        if variant == 4:
            return BinOp.DIV
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == BinOp.ADD:
            return
        if value == BinOp.SUB:
            return
        if value == BinOp.MUL:
            return
        if value == BinOp.DIV:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == BinOp.ADD:
            buf.write_i32(1)
        if value == BinOp.SUB:
            buf.write_i32(2)
        if value == BinOp.MUL:
            buf.write_i32(3)
        if value == BinOp.DIV:
            buf.write_i32(4)



class _UniffiFfiConverterSequenceTypeExpr(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterTypeExpr.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterTypeExpr.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterTypeExpr.read(buf) for i in range(count)
        ]

class _UniffiFfiConverterSequenceTypeStructInitializer(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterTypeStructInitializer.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterTypeStructInitializer.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterTypeStructInitializer.read(buf) for i in range(count)
        ]

@dataclass
class SwitchArm:
    def __init__(self, *, patterns:typing.List["Expr"], body:"Expr"):
        self.patterns = patterns
        self.body = body
        
        

    
    def __str__(self):
        return "SwitchArm(patterns={}, body={})".format(self.patterns, self.body)
    def __eq__(self, other):
        if self.patterns != other.patterns:
            return False
        if self.body != other.body:
            return False
        return True

class _UniffiFfiConverterTypeSwitchArm(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return SwitchArm(
            patterns=_UniffiFfiConverterSequenceTypeExpr.read(buf),
            body=_UniffiFfiConverterTypeExpr.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterSequenceTypeExpr.check_lower(value.patterns)
        _UniffiFfiConverterTypeExpr.check_lower(value.body)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterSequenceTypeExpr.write(value.patterns, buf)
        _UniffiFfiConverterTypeExpr.write(value.body, buf)

class _UniffiFfiConverterSequenceTypeSwitchArm(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterTypeSwitchArm.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterTypeSwitchArm.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterTypeSwitchArm.read(buf) for i in range(count)
        ]

class _UniffiFfiConverterSequenceString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterString.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterString.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterString.read(buf) for i in range(count)
        ]






class Stmt:
    def __init__(self):
        raise RuntimeError("Stmt cannot be instantiated directly")

    # Each enum variant is a nested class of the enum itself.
    @dataclass
    class LET:
        
        def __init__(self, *values):
            if len(values) != 2:
                raise TypeError(f"Expected 2 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"Stmt.LET{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, Stmt):
                return NotImplemented
            if not other.is_LET():
                return False
            return self._values == other._values

    @dataclass
    class EXPR:
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"Stmt.EXPR{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, Stmt):
                return NotImplemented
            if not other.is_EXPR():
                return False
            return self._values == other._values

    @dataclass
    class TAIL:
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"Stmt.TAIL{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, Stmt):
                return NotImplemented
            if not other.is_TAIL():
                return False
            return self._values == other._values

    

    # For each variant, we have `is_NAME` and `is_name` methods for easily checking
    # whether an instance is that variant.
    def is_LET(self) -> bool:
        return isinstance(self, Stmt.LET)
    def is_let(self) -> bool:
        return isinstance(self, Stmt.LET)
    def is_EXPR(self) -> bool:
        return isinstance(self, Stmt.EXPR)
    def is_expr(self) -> bool:
        return isinstance(self, Stmt.EXPR)
    def is_TAIL(self) -> bool:
        return isinstance(self, Stmt.TAIL)
    def is_tail(self) -> bool:
        return isinstance(self, Stmt.TAIL)
    

# Now, a little trick - we make each nested variant class be a subclass of the main
# enum class, so that method calls and instance checks etc will work intuitively.
# We might be able to do this a little more neatly with a metaclass, but this'll do.
Stmt.LET = type("Stmt.LET", (Stmt.LET, Stmt,), {})  # type: ignore
Stmt.EXPR = type("Stmt.EXPR", (Stmt.EXPR, Stmt,), {})  # type: ignore
Stmt.TAIL = type("Stmt.TAIL", (Stmt.TAIL, Stmt,), {})  # type: ignore




class _UniffiFfiConverterTypeStmt(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return Stmt.LET(
                _UniffiFfiConverterString.read(buf),
                _UniffiFfiConverterTypeExpr.read(buf),
            )
        if variant == 2:
            return Stmt.EXPR(
                _UniffiFfiConverterTypeExpr.read(buf),
            )
        if variant == 3:
            return Stmt.TAIL(
                _UniffiFfiConverterTypeExpr.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value.is_LET():
            _UniffiFfiConverterString.check_lower(value._values[0])
            _UniffiFfiConverterTypeExpr.check_lower(value._values[1])
            return
        if value.is_EXPR():
            _UniffiFfiConverterTypeExpr.check_lower(value._values[0])
            return
        if value.is_TAIL():
            _UniffiFfiConverterTypeExpr.check_lower(value._values[0])
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value.is_LET():
            buf.write_i32(1)
            _UniffiFfiConverterString.write(value._values[0], buf)
            _UniffiFfiConverterTypeExpr.write(value._values[1], buf)
        if value.is_EXPR():
            buf.write_i32(2)
            _UniffiFfiConverterTypeExpr.write(value._values[0], buf)
        if value.is_TAIL():
            buf.write_i32(3)
            _UniffiFfiConverterTypeExpr.write(value._values[0], buf)



class _UniffiFfiConverterSequenceTypeStmt(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterTypeStmt.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterTypeStmt.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterTypeStmt.read(buf) for i in range(count)
        ]






class Expr:
    def __init__(self):
        raise RuntimeError("Expr cannot be instantiated directly")

    # Each enum variant is a nested class of the enum itself.
    @dataclass
    class NUMBER:
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"Expr.NUMBER{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, Expr):
                return NotImplemented
            if not other.is_NUMBER():
                return False
            return self._values == other._values

    @dataclass
    class IDENT:
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"Expr.IDENT{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, Expr):
                return NotImplemented
            if not other.is_IDENT():
                return False
            return self._values == other._values

    @dataclass
    class STR:
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"Expr.STR{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, Expr):
                return NotImplemented
            if not other.is_STR():
                return False
            return self._values == other._values

    @dataclass
    class ENUM_VARIANT:
        
        def __init__(self, *values):
            if len(values) != 2:
                raise TypeError(f"Expected 2 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"Expr.ENUM_VARIANT{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, Expr):
                return NotImplemented
            if not other.is_ENUM_VARIANT():
                return False
            return self._values == other._values

    @dataclass
    class DOT_VARIANT:
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"Expr.DOT_VARIANT{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, Expr):
                return NotImplemented
            if not other.is_DOT_VARIANT():
                return False
            return self._values == other._values

    @dataclass
    class NEG:
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"Expr.NEG{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, Expr):
                return NotImplemented
            if not other.is_NEG():
                return False
            return self._values == other._values

    @dataclass
    class BINARY:
        
        def __init__(self, *values):
            if len(values) != 3:
                raise TypeError(f"Expected 3 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"Expr.BINARY{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, Expr):
                return NotImplemented
            if not other.is_BINARY():
                return False
            return self._values == other._values

    @dataclass
    class CALL:
        
        def __init__(self, *values):
            if len(values) != 2:
                raise TypeError(f"Expected 2 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"Expr.CALL{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, Expr):
                return NotImplemented
            if not other.is_CALL():
                return False
            return self._values == other._values

    @dataclass
    class METHOD_CALL:
        
        def __init__(self, *values):
            if len(values) != 3:
                raise TypeError(f"Expected 3 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"Expr.METHOD_CALL{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, Expr):
                return NotImplemented
            if not other.is_METHOD_CALL():
                return False
            return self._values == other._values

    @dataclass
    class FIELD:
        
        def __init__(self, *values):
            if len(values) != 2:
                raise TypeError(f"Expected 2 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"Expr.FIELD{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, Expr):
                return NotImplemented
            if not other.is_FIELD():
                return False
            return self._values == other._values

    @dataclass
    class INDEX:
        
        def __init__(self, *values):
            if len(values) != 2:
                raise TypeError(f"Expected 2 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"Expr.INDEX{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, Expr):
                return NotImplemented
            if not other.is_INDEX():
                return False
            return self._values == other._values

    @dataclass
    class STRUCT_LIT:
        
        def __init__(self, *values):
            if len(values) != 2:
                raise TypeError(f"Expected 2 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"Expr.STRUCT_LIT{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, Expr):
                return NotImplemented
            if not other.is_STRUCT_LIT():
                return False
            return self._values == other._values

    @dataclass
    class SWITCH:
        
        def __init__(self, *values):
            if len(values) != 2:
                raise TypeError(f"Expected 2 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"Expr.SWITCH{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, Expr):
                return NotImplemented
            if not other.is_SWITCH():
                return False
            return self._values == other._values

    @dataclass
    class FOR:
        
        def __init__(self, binders:typing.List[str], iter:Expr, body:typing.List["Stmt"]):
            self.binders = binders
            
            
            self.iter = iter
            
            
            self.body = body
            
            
            pass

    
            
            
    
        def __str__(self):
            return "Expr.FOR(binders={}, iter={}, body={})".format(self.binders, self.iter, self.body)
        def __eq__(self, other):
            if not isinstance(other, Expr):
                return NotImplemented
            if not other.is_FOR():
                return False
            if self.binders != other.binders:
                return False
            if self.iter != other.iter:
                return False
            if self.body != other.body:
                return False
            return True

    @dataclass
    class BLOCK:
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"Expr.BLOCK{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, Expr):
                return NotImplemented
            if not other.is_BLOCK():
                return False
            return self._values == other._values

    

    # For each variant, we have `is_NAME` and `is_name` methods for easily checking
    # whether an instance is that variant.
    def is_NUMBER(self) -> bool:
        return isinstance(self, Expr.NUMBER)
    def is_number(self) -> bool:
        return isinstance(self, Expr.NUMBER)
    def is_IDENT(self) -> bool:
        return isinstance(self, Expr.IDENT)
    def is_ident(self) -> bool:
        return isinstance(self, Expr.IDENT)
    def is_STR(self) -> bool:
        return isinstance(self, Expr.STR)
    def is_str(self) -> bool:
        return isinstance(self, Expr.STR)
    def is_ENUM_VARIANT(self) -> bool:
        return isinstance(self, Expr.ENUM_VARIANT)
    def is_enum_variant(self) -> bool:
        return isinstance(self, Expr.ENUM_VARIANT)
    def is_DOT_VARIANT(self) -> bool:
        return isinstance(self, Expr.DOT_VARIANT)
    def is_dot_variant(self) -> bool:
        return isinstance(self, Expr.DOT_VARIANT)
    def is_NEG(self) -> bool:
        return isinstance(self, Expr.NEG)
    def is_neg(self) -> bool:
        return isinstance(self, Expr.NEG)
    def is_BINARY(self) -> bool:
        return isinstance(self, Expr.BINARY)
    def is_binary(self) -> bool:
        return isinstance(self, Expr.BINARY)
    def is_CALL(self) -> bool:
        return isinstance(self, Expr.CALL)
    def is_call(self) -> bool:
        return isinstance(self, Expr.CALL)
    def is_METHOD_CALL(self) -> bool:
        return isinstance(self, Expr.METHOD_CALL)
    def is_method_call(self) -> bool:
        return isinstance(self, Expr.METHOD_CALL)
    def is_FIELD(self) -> bool:
        return isinstance(self, Expr.FIELD)
    def is_field(self) -> bool:
        return isinstance(self, Expr.FIELD)
    def is_INDEX(self) -> bool:
        return isinstance(self, Expr.INDEX)
    def is_index(self) -> bool:
        return isinstance(self, Expr.INDEX)
    def is_STRUCT_LIT(self) -> bool:
        return isinstance(self, Expr.STRUCT_LIT)
    def is_struct_lit(self) -> bool:
        return isinstance(self, Expr.STRUCT_LIT)
    def is_SWITCH(self) -> bool:
        return isinstance(self, Expr.SWITCH)
    def is_switch(self) -> bool:
        return isinstance(self, Expr.SWITCH)
    def is_FOR(self) -> bool:
        return isinstance(self, Expr.FOR)
    def is_for(self) -> bool:
        return isinstance(self, Expr.FOR)
    def is_BLOCK(self) -> bool:
        return isinstance(self, Expr.BLOCK)
    def is_block(self) -> bool:
        return isinstance(self, Expr.BLOCK)
    

# Now, a little trick - we make each nested variant class be a subclass of the main
# enum class, so that method calls and instance checks etc will work intuitively.
# We might be able to do this a little more neatly with a metaclass, but this'll do.
Expr.NUMBER = type("Expr.NUMBER", (Expr.NUMBER, Expr,), {})  # type: ignore
Expr.IDENT = type("Expr.IDENT", (Expr.IDENT, Expr,), {})  # type: ignore
Expr.STR = type("Expr.STR", (Expr.STR, Expr,), {})  # type: ignore
Expr.ENUM_VARIANT = type("Expr.ENUM_VARIANT", (Expr.ENUM_VARIANT, Expr,), {})  # type: ignore
Expr.DOT_VARIANT = type("Expr.DOT_VARIANT", (Expr.DOT_VARIANT, Expr,), {})  # type: ignore
Expr.NEG = type("Expr.NEG", (Expr.NEG, Expr,), {})  # type: ignore
Expr.BINARY = type("Expr.BINARY", (Expr.BINARY, Expr,), {})  # type: ignore
Expr.CALL = type("Expr.CALL", (Expr.CALL, Expr,), {})  # type: ignore
Expr.METHOD_CALL = type("Expr.METHOD_CALL", (Expr.METHOD_CALL, Expr,), {})  # type: ignore
Expr.FIELD = type("Expr.FIELD", (Expr.FIELD, Expr,), {})  # type: ignore
Expr.INDEX = type("Expr.INDEX", (Expr.INDEX, Expr,), {})  # type: ignore
Expr.STRUCT_LIT = type("Expr.STRUCT_LIT", (Expr.STRUCT_LIT, Expr,), {})  # type: ignore
Expr.SWITCH = type("Expr.SWITCH", (Expr.SWITCH, Expr,), {})  # type: ignore
Expr.FOR = type("Expr.FOR", (Expr.FOR, Expr,), {})  # type: ignore
Expr.BLOCK = type("Expr.BLOCK", (Expr.BLOCK, Expr,), {})  # type: ignore




class _UniffiFfiConverterTypeExpr(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return Expr.NUMBER(
                _UniffiFfiConverterFloat64.read(buf),
            )
        if variant == 2:
            return Expr.IDENT(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 3:
            return Expr.STR(
                _UniffiFfiConverterSequenceTypeStringPart.read(buf),
            )
        if variant == 4:
            return Expr.ENUM_VARIANT(
                _UniffiFfiConverterString.read(buf),
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 5:
            return Expr.DOT_VARIANT(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 6:
            return Expr.NEG(
                _UniffiFfiConverterBoxTypeExpr.read(buf),
            )
        if variant == 7:
            return Expr.BINARY(
                _UniffiFfiConverterBoxTypeExpr.read(buf),
                _UniffiFfiConverterTypeBinOp.read(buf),
                _UniffiFfiConverterBoxTypeExpr.read(buf),
            )
        if variant == 8:
            return Expr.CALL(
                _UniffiFfiConverterBoxTypeExpr.read(buf),
                _UniffiFfiConverterSequenceTypeExpr.read(buf),
            )
        if variant == 9:
            return Expr.METHOD_CALL(
                _UniffiFfiConverterBoxTypeExpr.read(buf),
                _UniffiFfiConverterString.read(buf),
                _UniffiFfiConverterSequenceTypeExpr.read(buf),
            )
        if variant == 10:
            return Expr.FIELD(
                _UniffiFfiConverterBoxTypeExpr.read(buf),
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 11:
            return Expr.INDEX(
                _UniffiFfiConverterBoxTypeExpr.read(buf),
                _UniffiFfiConverterBoxTypeExpr.read(buf),
            )
        if variant == 12:
            return Expr.STRUCT_LIT(
                _UniffiFfiConverterString.read(buf),
                _UniffiFfiConverterSequenceTypeStructInitializer.read(buf),
            )
        if variant == 13:
            return Expr.SWITCH(
                _UniffiFfiConverterBoxTypeExpr.read(buf),
                _UniffiFfiConverterSequenceTypeSwitchArm.read(buf),
            )
        if variant == 14:
            return Expr.FOR(
                _UniffiFfiConverterSequenceString.read(buf),
                _UniffiFfiConverterBoxTypeExpr.read(buf),
                _UniffiFfiConverterSequenceTypeStmt.read(buf),
            )
        if variant == 15:
            return Expr.BLOCK(
                _UniffiFfiConverterSequenceTypeStmt.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value.is_NUMBER():
            _UniffiFfiConverterFloat64.check_lower(value._values[0])
            return
        if value.is_IDENT():
            _UniffiFfiConverterString.check_lower(value._values[0])
            return
        if value.is_STR():
            _UniffiFfiConverterSequenceTypeStringPart.check_lower(value._values[0])
            return
        if value.is_ENUM_VARIANT():
            _UniffiFfiConverterString.check_lower(value._values[0])
            _UniffiFfiConverterString.check_lower(value._values[1])
            return
        if value.is_DOT_VARIANT():
            _UniffiFfiConverterString.check_lower(value._values[0])
            return
        if value.is_NEG():
            _UniffiFfiConverterBoxTypeExpr.check_lower(value._values[0])
            return
        if value.is_BINARY():
            _UniffiFfiConverterBoxTypeExpr.check_lower(value._values[0])
            _UniffiFfiConverterTypeBinOp.check_lower(value._values[1])
            _UniffiFfiConverterBoxTypeExpr.check_lower(value._values[2])
            return
        if value.is_CALL():
            _UniffiFfiConverterBoxTypeExpr.check_lower(value._values[0])
            _UniffiFfiConverterSequenceTypeExpr.check_lower(value._values[1])
            return
        if value.is_METHOD_CALL():
            _UniffiFfiConverterBoxTypeExpr.check_lower(value._values[0])
            _UniffiFfiConverterString.check_lower(value._values[1])
            _UniffiFfiConverterSequenceTypeExpr.check_lower(value._values[2])
            return
        if value.is_FIELD():
            _UniffiFfiConverterBoxTypeExpr.check_lower(value._values[0])
            _UniffiFfiConverterString.check_lower(value._values[1])
            return
        if value.is_INDEX():
            _UniffiFfiConverterBoxTypeExpr.check_lower(value._values[0])
            _UniffiFfiConverterBoxTypeExpr.check_lower(value._values[1])
            return
        if value.is_STRUCT_LIT():
            _UniffiFfiConverterString.check_lower(value._values[0])
            _UniffiFfiConverterSequenceTypeStructInitializer.check_lower(value._values[1])
            return
        if value.is_SWITCH():
            _UniffiFfiConverterBoxTypeExpr.check_lower(value._values[0])
            _UniffiFfiConverterSequenceTypeSwitchArm.check_lower(value._values[1])
            return
        if value.is_FOR():
            _UniffiFfiConverterSequenceString.check_lower(value.binders)
            _UniffiFfiConverterBoxTypeExpr.check_lower(value.iter)
            _UniffiFfiConverterSequenceTypeStmt.check_lower(value.body)
            return
        if value.is_BLOCK():
            _UniffiFfiConverterSequenceTypeStmt.check_lower(value._values[0])
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value.is_NUMBER():
            buf.write_i32(1)
            _UniffiFfiConverterFloat64.write(value._values[0], buf)
        if value.is_IDENT():
            buf.write_i32(2)
            _UniffiFfiConverterString.write(value._values[0], buf)
        if value.is_STR():
            buf.write_i32(3)
            _UniffiFfiConverterSequenceTypeStringPart.write(value._values[0], buf)
        if value.is_ENUM_VARIANT():
            buf.write_i32(4)
            _UniffiFfiConverterString.write(value._values[0], buf)
            _UniffiFfiConverterString.write(value._values[1], buf)
        if value.is_DOT_VARIANT():
            buf.write_i32(5)
            _UniffiFfiConverterString.write(value._values[0], buf)
        if value.is_NEG():
            buf.write_i32(6)
            _UniffiFfiConverterBoxTypeExpr.write(value._values[0], buf)
        if value.is_BINARY():
            buf.write_i32(7)
            _UniffiFfiConverterBoxTypeExpr.write(value._values[0], buf)
            _UniffiFfiConverterTypeBinOp.write(value._values[1], buf)
            _UniffiFfiConverterBoxTypeExpr.write(value._values[2], buf)
        if value.is_CALL():
            buf.write_i32(8)
            _UniffiFfiConverterBoxTypeExpr.write(value._values[0], buf)
            _UniffiFfiConverterSequenceTypeExpr.write(value._values[1], buf)
        if value.is_METHOD_CALL():
            buf.write_i32(9)
            _UniffiFfiConverterBoxTypeExpr.write(value._values[0], buf)
            _UniffiFfiConverterString.write(value._values[1], buf)
            _UniffiFfiConverterSequenceTypeExpr.write(value._values[2], buf)
        if value.is_FIELD():
            buf.write_i32(10)
            _UniffiFfiConverterBoxTypeExpr.write(value._values[0], buf)
            _UniffiFfiConverterString.write(value._values[1], buf)
        if value.is_INDEX():
            buf.write_i32(11)
            _UniffiFfiConverterBoxTypeExpr.write(value._values[0], buf)
            _UniffiFfiConverterBoxTypeExpr.write(value._values[1], buf)
        if value.is_STRUCT_LIT():
            buf.write_i32(12)
            _UniffiFfiConverterString.write(value._values[0], buf)
            _UniffiFfiConverterSequenceTypeStructInitializer.write(value._values[1], buf)
        if value.is_SWITCH():
            buf.write_i32(13)
            _UniffiFfiConverterBoxTypeExpr.write(value._values[0], buf)
            _UniffiFfiConverterSequenceTypeSwitchArm.write(value._values[1], buf)
        if value.is_FOR():
            buf.write_i32(14)
            _UniffiFfiConverterSequenceString.write(value.binders, buf)
            _UniffiFfiConverterBoxTypeExpr.write(value.iter, buf)
            _UniffiFfiConverterSequenceTypeStmt.write(value.body, buf)
        if value.is_BLOCK():
            buf.write_i32(15)
            _UniffiFfiConverterSequenceTypeStmt.write(value._values[0], buf)



@dataclass
class StructInitializer:
    def __init__(self, *, label:str, value:"Expr"):
        self.label = label
        self.value = value
        
        

    
    def __str__(self):
        return "StructInitializer(label={}, value={})".format(self.label, self.value)
    def __eq__(self, other):
        if self.label != other.label:
            return False
        if self.value != other.value:
            return False
        return True

class _UniffiFfiConverterTypeStructInitializer(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return StructInitializer(
            label=_UniffiFfiConverterString.read(buf),
            value=_UniffiFfiConverterTypeExpr.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.label)
        _UniffiFfiConverterTypeExpr.check_lower(value.value)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.label, buf)
        _UniffiFfiConverterTypeExpr.write(value.value, buf)

class _UniffiFfiConverterOptionalTypeParam(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterTypeParam.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterTypeParam.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterTypeParam.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

class _UniffiFfiConverterSequenceTypeInterfaceMethod(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterTypeInterfaceMethod.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterTypeInterfaceMethod.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterTypeInterfaceMethod.read(buf) for i in range(count)
        ]






class Item:
    def __init__(self):
        raise RuntimeError("Item cannot be instantiated directly")

    # Each enum variant is a nested class of the enum itself.
    @dataclass
    class LET:
        
        def __init__(self, *values):
            if len(values) != 2:
                raise TypeError(f"Expected 2 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"Item.LET{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, Item):
                return NotImplemented
            if not other.is_LET():
                return False
            return self._values == other._values

    @dataclass
    class ENUM:
        
        def __init__(self, name:str, variants:typing.List[str]):
            self.name = name
            
            
            self.variants = variants
            
            
            pass

    
            
            
    
        def __str__(self):
            return "Item.ENUM(name={}, variants={})".format(self.name, self.variants)
        def __eq__(self, other):
            if not isinstance(other, Item):
                return NotImplemented
            if not other.is_ENUM():
                return False
            if self.name != other.name:
                return False
            if self.variants != other.variants:
                return False
            return True

    @dataclass
    class STRUCT:
        
        def __init__(self, name:str, fields:typing.List[Param]):
            self.name = name
            
            
            self.fields = fields
            
            
            pass

    
            
            
    
        def __str__(self):
            return "Item.STRUCT(name={}, fields={})".format(self.name, self.fields)
        def __eq__(self, other):
            if not isinstance(other, Item):
                return NotImplemented
            if not other.is_STRUCT():
                return False
            if self.name != other.name:
                return False
            if self.fields != other.fields:
                return False
            return True

    @dataclass
    class FN:
        
        def __init__(self, receiver:typing.Optional[Param], name:str, params:typing.List[Param], body:typing.List["Stmt"]):
            self.receiver = receiver
            
            
            self.name = name
            
            
            self.params = params
            
            
            self.body = body
            
            
            pass

    
            
            
    
        def __str__(self):
            return "Item.FN(receiver={}, name={}, params={}, body={})".format(self.receiver, self.name, self.params, self.body)
        def __eq__(self, other):
            if not isinstance(other, Item):
                return NotImplemented
            if not other.is_FN():
                return False
            if self.receiver != other.receiver:
                return False
            if self.name != other.name:
                return False
            if self.params != other.params:
                return False
            if self.body != other.body:
                return False
            return True

    @dataclass
    class INTERFACE:
        
        def __init__(self, name:str, methods:typing.List[InterfaceMethod]):
            self.name = name
            
            
            self.methods = methods
            
            
            pass

    
            
            
    
        def __str__(self):
            return "Item.INTERFACE(name={}, methods={})".format(self.name, self.methods)
        def __eq__(self, other):
            if not isinstance(other, Item):
                return NotImplemented
            if not other.is_INTERFACE():
                return False
            if self.name != other.name:
                return False
            if self.methods != other.methods:
                return False
            return True

    

    # For each variant, we have `is_NAME` and `is_name` methods for easily checking
    # whether an instance is that variant.
    def is_LET(self) -> bool:
        return isinstance(self, Item.LET)
    def is_let(self) -> bool:
        return isinstance(self, Item.LET)
    def is_ENUM(self) -> bool:
        return isinstance(self, Item.ENUM)
    def is_enum(self) -> bool:
        return isinstance(self, Item.ENUM)
    def is_STRUCT(self) -> bool:
        return isinstance(self, Item.STRUCT)
    def is_struct(self) -> bool:
        return isinstance(self, Item.STRUCT)
    def is_FN(self) -> bool:
        return isinstance(self, Item.FN)
    def is_fn(self) -> bool:
        return isinstance(self, Item.FN)
    def is_INTERFACE(self) -> bool:
        return isinstance(self, Item.INTERFACE)
    def is_interface(self) -> bool:
        return isinstance(self, Item.INTERFACE)
    

# Now, a little trick - we make each nested variant class be a subclass of the main
# enum class, so that method calls and instance checks etc will work intuitively.
# We might be able to do this a little more neatly with a metaclass, but this'll do.
Item.LET = type("Item.LET", (Item.LET, Item,), {})  # type: ignore
Item.ENUM = type("Item.ENUM", (Item.ENUM, Item,), {})  # type: ignore
Item.STRUCT = type("Item.STRUCT", (Item.STRUCT, Item,), {})  # type: ignore
Item.FN = type("Item.FN", (Item.FN, Item,), {})  # type: ignore
Item.INTERFACE = type("Item.INTERFACE", (Item.INTERFACE, Item,), {})  # type: ignore




class _UniffiFfiConverterTypeItem(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return Item.LET(
                _UniffiFfiConverterString.read(buf),
                _UniffiFfiConverterTypeExpr.read(buf),
            )
        if variant == 2:
            return Item.ENUM(
                _UniffiFfiConverterString.read(buf),
                _UniffiFfiConverterSequenceString.read(buf),
            )
        if variant == 3:
            return Item.STRUCT(
                _UniffiFfiConverterString.read(buf),
                _UniffiFfiConverterSequenceTypeParam.read(buf),
            )
        if variant == 4:
            return Item.FN(
                _UniffiFfiConverterOptionalTypeParam.read(buf),
                _UniffiFfiConverterString.read(buf),
                _UniffiFfiConverterSequenceTypeParam.read(buf),
                _UniffiFfiConverterSequenceTypeStmt.read(buf),
            )
        if variant == 5:
            return Item.INTERFACE(
                _UniffiFfiConverterString.read(buf),
                _UniffiFfiConverterSequenceTypeInterfaceMethod.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value.is_LET():
            _UniffiFfiConverterString.check_lower(value._values[0])
            _UniffiFfiConverterTypeExpr.check_lower(value._values[1])
            return
        if value.is_ENUM():
            _UniffiFfiConverterString.check_lower(value.name)
            _UniffiFfiConverterSequenceString.check_lower(value.variants)
            return
        if value.is_STRUCT():
            _UniffiFfiConverterString.check_lower(value.name)
            _UniffiFfiConverterSequenceTypeParam.check_lower(value.fields)
            return
        if value.is_FN():
            _UniffiFfiConverterOptionalTypeParam.check_lower(value.receiver)
            _UniffiFfiConverterString.check_lower(value.name)
            _UniffiFfiConverterSequenceTypeParam.check_lower(value.params)
            _UniffiFfiConverterSequenceTypeStmt.check_lower(value.body)
            return
        if value.is_INTERFACE():
            _UniffiFfiConverterString.check_lower(value.name)
            _UniffiFfiConverterSequenceTypeInterfaceMethod.check_lower(value.methods)
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value.is_LET():
            buf.write_i32(1)
            _UniffiFfiConverterString.write(value._values[0], buf)
            _UniffiFfiConverterTypeExpr.write(value._values[1], buf)
        if value.is_ENUM():
            buf.write_i32(2)
            _UniffiFfiConverterString.write(value.name, buf)
            _UniffiFfiConverterSequenceString.write(value.variants, buf)
        if value.is_STRUCT():
            buf.write_i32(3)
            _UniffiFfiConverterString.write(value.name, buf)
            _UniffiFfiConverterSequenceTypeParam.write(value.fields, buf)
        if value.is_FN():
            buf.write_i32(4)
            _UniffiFfiConverterOptionalTypeParam.write(value.receiver, buf)
            _UniffiFfiConverterString.write(value.name, buf)
            _UniffiFfiConverterSequenceTypeParam.write(value.params, buf)
            _UniffiFfiConverterSequenceTypeStmt.write(value.body, buf)
        if value.is_INTERFACE():
            buf.write_i32(5)
            _UniffiFfiConverterString.write(value.name, buf)
            _UniffiFfiConverterSequenceTypeInterfaceMethod.write(value.methods, buf)



class _UniffiFfiConverterSequenceTypeItem(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterTypeItem.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterTypeItem.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterTypeItem.read(buf) for i in range(count)
        ]
def parse(text: str) -> typing.List[Item]:
    
    _UniffiFfiConverterString.check_lower(text)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(text),
    )
    _uniffi_lift_return = _UniffiFfiConverterSequenceTypeItem.lift
    _uniffi_error_converter = None
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_kon_parser_fn_func_parse,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)

__all__ = [
    "InternalError",
    "StringPart",
    "BinOp",
    "Stmt",
    "Expr",
    "Item",
    "Param",
    "InterfaceMethod",
    "SwitchArm",
    "StructInitializer",
    "parse",
]